server:
  port: 6604


#服务名
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      routes:
        - id:  apiuser
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
          uri: lb://user-service
          predicates:
          # 重点！转发该路径！,/userapi/**,
          - Path=/userapi/**
          # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
          #而不是我们期望的去掉userapi，只保留**部分
          filters:
          - StripPrefix=1
        - id: apisocket
         # 重点！lb:ws://代表从注册中心获取服务，并且转发协议为websocket，这种格式怀疑人生！
         # lb:ws://notification-service
          uri: lb://bullet
          predicates:
           # 转发/bullet端点下的所有路径
          - Path=/bullet/info/**
        - id: apisocket
         # 重点！lb:ws://代表从注册中心获取服务，并且转发协议为websocket，这种格式怀疑人生！
         # lb:ws://notification-service
          uri: lb:ws://bullet
          predicates:
           # 转发/bullet端点下的所有路径
          - Path=/bullet/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7700/eureka/



security:
  user:
    password: none
  basic:
    enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG